Event.Item = {
	START_MOVING: "ITEM.START_MOVING",
	FINISH_MOVING: "ITEM.FINISH_MOVING",
	MOVE_TO: "ITEM.MOVE_TO",
	SELECT: "ITEM.SELECT",
	UNSELECT: "ITEM.UNSELECT"
};

Event.Page = {
	START_DRAWING: "PAGE.START_DRAWING",
	STOP_DRAWING: "PAGE.STOP_DRAWING",
	FINISH_DRAWING: "PAGE.FINISH_DRAWING",
	DRAW_TO: "PAGE.DRAW_TO",

	START_SELECTING_COLOR: "PAGE.START_SELECTING_COLOR",

	START_MOVING: "PAGE.START_MOVING",
	MOVE_TO: "PAGE.MOVE_TO",
	FINISH_MOVING: "PAGE.FINISH_MOVING",

	START_TEXTING: "PAGE.START_TEXTING",
	FINISH_TEXTING: "PAGE.FINISH_TEXTING",
};